# Introduction to NumPy

NumPy is a vital Python library for numerical computing. It offers efficient multidimensional array operations, math functions, and linear algebra tools. Its memory efficiency, random number generation, and seamless integration with other libraries make it indispensable for data analysis, simulations, and scientific computations. All array operations are done in C and are hence much faster than normal arrays. <br />
NumPy is going to form the foundation of turning your data into a series of numbers and then what a machine learning algorithm will do is work out the patterns in those numbers.

In [35]:
import numpy as np

## DataTypes and Attributes

In [36]:
# NumPy's main datatype is ndarray (n-dimensional array)
a1 = np.array([1, 2, 3])
a1 # One dimensional array (vector)

array([1, 2, 3])

In [37]:
type(a1)

numpy.ndarray

In [38]:
a2 = np.array([
    [1, 2.0, 3.4],
    [4, 5, 6.5]
])
a2 # Two dimensional array (matrix)

array([[1. , 2. , 3.4],
       [4. , 5. , 6.5]])

In [39]:
a3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])
a3 # 3-dimensional array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

- Axis = 0 -> Z Axis
- Axis = 1 -> X Axis
- Axis = 2 -> Y Axis

In [40]:
a1.shape

(3,)

In [41]:
a2.shape

(2, 3)

In [42]:
a3.shape

(2, 3, 3)

In [43]:
a1.ndim, a2.ndim, a3.ndim # Returns the number of dimensions

(1, 2, 3)

In [44]:
a1.ndim

1

In [45]:
a1.size, a2.size, a3.size, a1.dtype, a2.dtype, a3.dtype

(3, 6, 18, dtype('int64'), dtype('float64'), dtype('int64'))

In [46]:
# Create a dataframe from a numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.4
1  4.0  5.0  6.5

## Creating arrays

In [47]:
ones = np.ones((2, 3))

In [48]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
zeroes = np.zeros(a3.shape)
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [50]:
zeroes = np.zeros((2, 3, 3, 3))
zeroes

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [51]:
range_array = np.arange(0, 10, 2)

In [52]:
range_array

array([0, 2, 4, 6, 8])

In [53]:
random_array = np.random.randint(3, 10, size=(3, 5))
random_array

array([[8, 4, 3, 9, 6],
       [6, 9, 6, 8, 4],
       [4, 8, 7, 3, 8]])

In [65]:
# Pseudo random numbers 
np.random.seed(0)
# Random seed number allows the number to not change everytime we run the code. 
# It makes it align with the seed. We can generate reproducible random numbers.
rand_arr = np.random.randint(10, size=(5, 3))
rand_arr

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [85]:
rand_arr = np.random.randint(10, size=(5, 3))
rand_arr

array([[0, 6, 4],
       [2, 4, 6],
       [3, 3, 7],
       [8, 5, 0],
       [8, 5, 4]])

## Viewing arrays and matrices

In [86]:
# Get unique numbers
np.unique(rand_arr)

array([0, 2, 3, 4, 5, 6, 7, 8])

In [89]:
a3[:2, :2, :1]

array([[[ 1],
        [ 4]],

       [[10],
        [13]]])

In [88]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [90]:
a1

array([1, 2, 3])

In [93]:
a1[2] # One dimensional and two dimensional indexing is the same as python arrays

3

In [95]:
a2[0][2]

3.4

In [96]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [98]:
a3[0][1][1]

5

In [99]:
a3.shape

(2, 3, 3)

In [101]:
test_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
test_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [102]:
test_arr.shape

(2, 2, 3)

In [103]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [104]:
a3.shape

(2, 3, 3)

In [109]:
a2[1][1]

5.0

In [110]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [111]:
a3.shape

(2, 3, 3)

In [112]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))

In [114]:
a4

array([[[[7, 4, 1, 3, 3],
         [9, 2, 5, 2, 3],
         [5, 7, 2, 7, 1],
         [6, 5, 0, 0, 3]],

        [[1, 9, 9, 6, 6],
         [7, 8, 8, 7, 0],
         [8, 6, 8, 9, 8],
         [3, 6, 1, 7, 4]],

        [[9, 2, 0, 8, 2],
         [7, 8, 4, 4, 1],
         [7, 6, 9, 4, 1],
         [5, 9, 7, 1, 3]]],


       [[[5, 7, 3, 6, 6],
         [7, 9, 1, 9, 6],
         [0, 3, 8, 4, 1],
         [4, 5, 0, 3, 1]],

        [[4, 4, 4, 0, 0],
         [8, 4, 6, 9, 3],
         [3, 2, 1, 2, 1],
         [3, 4, 1, 1, 0]],

        [[7, 8, 4, 3, 5],
         [6, 3, 2, 9, 8],
         [1, 4, 0, 8, 3],
         [9, 5, 5, 1, 7]]]])

In [123]:
a4[:, :, :, :1] # Get the first 4 numbers of the inner most arrays

array([[[[7],
         [9],
         [5],
         [6]],

        [[1],
         [7],
         [8],
         [3]],

        [[9],
         [7],
         [7],
         [5]]],


       [[[5],
         [7],
         [0],
         [4]],

        [[4],
         [8],
         [3],
         [3]],

        [[7],
         [6],
         [1],
         [9]]]])

In [125]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])