# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.random.randint(1, 10, size=(3))

# Create a 2-dimensional NumPy array using np.array()
a2 = np.random.randint(1, 10, size=(2, 3))

# Create a 3-dimensional Numpy array using np.array()
a3 = np.random.randint(1, 10, size=(2, 2, 3))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.ndim, a1.dtype, a1.size, type(a1)

(1, dtype('int64'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.ndim, a2.dtype, a2.size, type(a2)

(2, dtype('int64'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.ndim, a3.dtype, a3.size, type(a3)

(3, dtype('int64'), 12, numpy.ndarray)

In [8]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
a2_df = pd.DataFrame(a2, index=["row1", "row2"], columns=["col1", "col2", "col3"])
a2_df

col1  col2  col3
row1     4     8     8
row2     2     9     4

In [10]:
# Create an array of shape (10, 2) with only ones
ones_arr = np.ones((10, 2), dtype=int)
ones_arr

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [12]:
# Create an array of shape (7, 2, 3) of only zeros
z_arr = np.zeros((7, 2, 3), dtype=int)
z_arr

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [16]:
# Create an array within a range of 0 and 100 with step 3
range_arr = np.arange(0, 100, 3)
range_arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [18]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_arr = np.random.randint(0, 10, size=(7, 2))
rand_arr

array([[9, 4],
       [2, 5],
       [4, 3],
       [2, 7],
       [5, 6],
       [1, 9],
       [8, 4]])

In [21]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
float_random_arr = np.random.rand(3, 5)
float_random_arr

array([[0.27054826, 0.68615999, 0.30458948, 0.94100536, 0.58997622],
       [0.18742432, 0.30615366, 0.92190792, 0.57105181, 0.20487597],
       [0.86570939, 0.79713187, 0.56931728, 0.60347214, 0.04661968]])

In [27]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
ran_arr = np.random.randint(0, 10, size=(4, 6))
ran_arr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens? Are the numbers in the array different or the same? Why do think this is?
- The numbers are the same
- This is because we set a seed and the random numbers are actually pseudo random. Normally, the seed is randomly chosen but now that we have explicitly specified it, the random numbers will always be the same.

In [28]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
not_unique_arr = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
unique_arr = np.unique(not_unique_arr)
unique_arr

array([1, 2, 3, 4, 5, 7, 9])

In [30]:
# Find the 0'th index of the latest array you created
not_unique_arr[0]

array([9, 1, 3, 7, 4, 9, 3])

In [32]:
not_unique_arr

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [33]:
# Get the first 2 rows of latest array you created
not_unique_arr[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [41]:
# Get the first 2 values of the first 2 rows of the latest array
not_unique_arr[:2, :2]

array([[9, 1],
       [5, 3]])

## Difference
`[:2, :2]`:

This expression is used for slicing multidimensional arrays. It selects the first two rows and the first two columns of the array.

In a 2-dimensional array, the first index refers to rows, and the second index refers to columns. Therefore, `[:2, :2]` selects the elements from the first two rows and the first two columns.

`[:2][:2]`:

This expression first applies slicing `[:2]` on the array, which gives you the first two rows. Then, it applies another `[:2]` on the result of the first slicing.

The first `[:2]` selects the first two rows. Applying `[:2]` again on this result doesn't change anything because the result is already a 2x3 array.

In [42]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr1 = np.random.randint(0, 10, size=(3, 5))
arr2 = np.ones((3, 5))

In [43]:
# Add the two arrays together
arr1 + arr2

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [44]:
# Create another array of ones of shape (5, 3)
arr3 = np.ones((5, 3))

In [45]:
# Try add the array of ones and the other most recent array together
arr1 + arr2 + arr3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?
How would you fix it?
- The error is caused because the shapes are different.
- I can fix this error by transposing the (5, 3) shape to (3, 5).

In [46]:
# Create another array of ones of shape (3, 5)
arr4 = np.ones((3, 5))

In [48]:
# Subtract the new array of ones from the other most recent array
new_arr = (arr1 + arr2) - arr4
new_arr

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [51]:
# Multiply the ones array with the latest array
new_arr = new_arr * (arr3.transpose())
new_arr

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [52]:
# Take the latest array to the power of 2 using '**'
new_arr = new_arr ** 2
new_arr

array([[36., 49.,  4.,  0.,  9.],
       [ 1., 49.,  9.,  1., 25.],
       [25., 81.,  9., 25.,  1.]])

In [53]:
# Do the same thing with np.square()
np.square(new_arr)

array([[1.296e+03, 2.401e+03, 1.600e+01, 0.000e+00, 8.100e+01],
       [1.000e+00, 2.401e+03, 8.100e+01, 1.000e+00, 6.250e+02],
       [6.250e+02, 6.561e+03, 8.100e+01, 6.250e+02, 1.000e+00]])

In [54]:
# Find the mean of the latest array using np.mean()
np.mean(new_arr)

21.6

In [55]:
# Find the maximum of the latest array using np.max()
np.max(new_arr)

81.0

In [56]:
# Find the minimum of the latest array using np.min()
np.min(new_arr)

0.0

In [57]:
# Find the standard deviation of the latest array
np.std(new_arr)

22.8

In [59]:
# Find the variance of the latest array
np.var(new_arr)

519.84

In [63]:
new_arr

array([[36., 49.,  4.,  0.,  9.],
       [ 1., 49.,  9.,  1., 25.],
       [25., 81.,  9., 25.,  1.]])

In [66]:
# Reshape the latest array to (3, 5, 1)
new_arr = new_arr.reshape((3, 5, 1))

In [67]:
new_arr

array([[[36.],
        [49.],
        [ 4.],
        [ 0.],
        [ 9.]],

       [[ 1.],
        [49.],
        [ 9.],
        [ 1.],
        [25.]],

       [[25.],
        [81.],
        [ 9.],
        [25.],
        [ 1.]]])

In [68]:
# Transpose the latest array
new_arr = new_arr.T # Can also use .transpose()
new_arr

array([[[36.,  1., 25.],
        [49., 49., 81.],
        [ 4.,  9.,  9.],
        [ 0.,  1., 25.],
        [ 9., 25.,  1.]]])

What does the transpose do?
- Switches the rows and the columns

In [69]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
r_arr_1 = np.random.randint(0, 10, size=(3, 3))
r_arr_2 = np.random.randint(0, 10, size=(3, 2))

In [70]:
r_arr_1

array([[9, 1, 9],
       [3, 7, 6],
       [8, 7, 4]])

In [71]:
r_arr_2

array([[1, 4],
       [7, 9],
       [8, 8]])

In [73]:
# Perform a dot product on the two newest arrays you created
dot_arr = np.dot(r_arr_1, r_arr_2)
dot_arr

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [74]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
r_arr_1 = np.random.randint(0, 10, size=(4, 3))
r_arr_2 = np.random.randint(0, 10, size=(4, 2))

In [75]:
# Perform a dot product on the two newest arrays you created
dot_arr = np.dot(r_arr_1, r_arr_2)
dot_arr

ValueError: shapes (4,3) and (4,2) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?
- I will fix it by aligning the shape.
- For that I will transpose the first array with (4, 3) shape to (3, 4).

In [76]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
dot_arr = np.dot(r_arr_1.T, r_arr_2)
dot_arr

array([[ 74, 135],
       [142, 168],
       [ 40,  30]])

In [77]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
r_arr_1 = np.random.randint(0, 10, size=(3, 3))
r_arr_2 = np.random.randint(0, 10, size=(3, 3))

In [78]:
# Compare the two arrays with '>'
r_arr_1 > r_arr_2

array([[ True,  True, False],
       [False,  True,  True],
       [ True,  True, False]])

In [79]:
# Compare the two arrays with '>='
r_arr_1 >= r_arr_2

array([[ True,  True, False],
       [ True,  True,  True],
       [ True,  True, False]])

In [80]:
# Find which elements of the first array are greater than 7
r_arr_1 > 7

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [81]:
# Which parts of each array are equal? (try using '==')
r_arr_1 == r_arr_2

array([[False, False, False],
       [ True, False, False],
       [False, False, False]])

In [82]:
# Sort one of the arrays you just created in ascending order
np.sort(r_arr_1)

array([[1, 7, 8],
       [0, 6, 6],
       [2, 4, 7]])

In [83]:
# Sort the indexes of one of the arrays you just created
np.argsort(r_arr_1)

array([[2, 1, 0],
       [0, 1, 2],
       [2, 1, 0]])

In [84]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(r_arr_1)

0

In [85]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(r_arr_1)

3

In [86]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(r_arr_1, axis=1)

array([0, 1, 0])

In [87]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(r_arr_1, axis=0)

array([0, 0, 1])

In [88]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[ 1.49543425,  0.33818125,  3.37229625, -0.92039081, -0.39863839],
       [-0.06086409, -1.41875046,  1.04249162,  0.90353249,  0.01900033],
       [-0.53441645, -1.49505387, -0.78925833,  0.74371128, -0.21216142]])


Normally distributed random numbers, also known as Gaussian random numbers, follow a probability distribution known as the normal distribution. This distribution is characterized by a bell-shaped curve, where the majority of observations cluster around the mean, and the probabilities of observations decrease symmetrically as you move away from the mean.

In [89]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.